# Generated by Django 3.2.6 on 2023-08-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('open', models.DecimalField(decimal_places=14, max_digits=18, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('close', models.DecimalField(decimal_places=14, max_digits=18, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('dividends', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('stock_splits', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('open', models.DecimalField(decimal_places=14, max_digits=18, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('close', models.DecimalField(decimal_places=14, max_digits=18, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('dividends', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('stock_splits', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockDividendYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150)),
                ('exchange_name', models.CharField(blank=True, max_length=150)),
                ('date_indicator', models.DateTimeField(null=True)),
                ('dividend_yield', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150)),
                ('exchange_name', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
