# Generated by Django 3.2.6 on 2023-07-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('open', models.DecimalField(decimal_places=14, max_digits=18, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('close', models.DecimalField(decimal_places=14, max_digits=18, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('dividends', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('stock_splits', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('dataticket', models.IntegerField(null=True)),
            ],
        ),
    ]
