# Generated by Django 3.2.6 on 2023-08-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
