# Generated by Django 3.2.6 on 2023-07-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_market_dataticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
