# Generated by Django 3.2.6 on 2023-07-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_market_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
