# Generated by Django 3.2.6 on 2023-08-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_market_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=10)),
                ('exchange_name', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
