# Generated by Django 3.2.6 on 2023-08-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stocklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='exchange_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
