# Generated by Django 3.2.6 on 2023-08-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230808_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDividendYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150)),
                ('exchange_name', models.CharField(blank=True, max_length=150)),
                ('date_indicator', models.DateTimeField(null=True)),
                ('dividend_yield', models.DecimalField(decimal_places=14, max_digits=18, null=True)),
            ],
        ),
    ]
