# Generated by Django 3.2.6 on 2023-08-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_stockdividendyield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdividendyield',
            name='dividend_yield',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
    ]
