# Generated by Django 3.2.6 on 2023-08-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_stockdividendyield_dividend_yield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('open', models.DecimalField(decimal_places=14, max_digits=18, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('close', models.DecimalField(decimal_places=14, max_digits=18, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('dividends', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('stock_splits', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
