# Generated by Django 3.2.6 on 2023-08-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
